# Scheduled Content Sync
#
# This workflow syncs content from Dev.to on a daily schedule.
# Articles are pulled to the 'live' branch automatically.
#
# Setup:
# 1. Add VIBE_FOREM_API_KEY to your repository secrets
# 2. Copy this file to .github/workflows/scheduled-sync.yml

name: Scheduled Content Sync

on:
  schedule:
    # Run daily at 6:00 AM UTC
    - cron: '0 6 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull Dev.to articles
        id: puller
        uses: socialsbase/puller-action@v1
        env:
          VIBE_FOREM_API_KEY: ${{ secrets.VIBE_FOREM_API_KEY }}
        with:
          platform: devto
          output-dir: content/devto
          branch: live
          exclude-drafts: true

      - name: Report results
        run: |
          echo "## Sync Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Pulled | ${{ steps.puller.outputs.pulled-count }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Skipped | ${{ steps.puller.outputs.skipped-count }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Committed | ${{ steps.puller.outputs.committed }} |" >> $GITHUB_STEP_SUMMARY

          if [ "${{ steps.puller.outputs.committed }}" = "true" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Commit: \`${{ steps.puller.outputs.commit-sha }}\`" >> $GITHUB_STEP_SUMMARY
          fi
